; unused while doing the labeling, but here for reference

BUTTON_A := $01
BUTTON_B := $02
BUTTON_SELECT := $04
BUTTON_START := $08
BUTTON_UP := $10
BUTTON_DOWN := $20
BUTTON_LEFT := $40
BUTTON_RIGHT := $80

BUTTON_DPAD := BUTTON_UP | BUTTON_DOWN | BUTTON_LEFT | BUTTON_RIGHT

; gameState values
GAMESTATE_LEADERBOARD := $F8
GAMESTATE_GAMEOVER := $F9
GAMESTATE_TITLE := $FA
GAMESTATE_DEMO := $FB
GAMESTATE_GAME_TYPE := $FC
GAMESTATE_LEVEL_SELECT := $FD
GAMESTATE_HANDICAP := $FE
GAMESTATE_MUSIC_SELECT := $FF
GAMESTATE_PLAYING := $00
GAMESTATE_PAUSED := $01